version: 2
jobs:
  build:
#    brances:
#      only:
#        - testing
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialise Terraform
          command: terraform init
      - run:
          name: Kick off Terraform
          command: terraform apply --auto-approve